# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kibali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_key', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
