# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kibali', '0003_signatureconfiguration_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureconfiguration',
            name='allowed_domains',
            field=models.TextField(default='.*', help_text='List the domains that are allowed to submit data for approval. Each domain should go on its own line. You can use regular expressions.'),
        ),
        migrations.AlterField(
            model_name='signatureconfiguration',
            name='application_key',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='signatureconfiguration',
            name='label',
            field=models.TextField(help_text='The human-readable name for the application using the signatures. Primarily used for record-keeping and organization.'),
        ),
    ]
