# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibali', '0004_signatureconfirmation__add__application_key__allowed_domains__label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatureconfiguration',
            name='redirect_url',
        ),
        migrations.AddField(
            model_name='signatureconfiguration',
            name='created_callback_url',
            field=models.URLField(blank=True, help_text='The URL to which the package data will be forwarded after being received.', null=True),
        ),
        migrations.AddField(
            model_name='signatureconfiguration',
            name='created_redirect_url',
            field=models.URLField(blank=True, help_text='The page to which the user will be redirected after data is submitted to the system, if by form POST. If this is left blank, a default page will be used.', null=True),
        ),
        migrations.AddField(
            model_name='signatureconfiguration',
            name='signed_callback_url',
            field=models.URLField(blank=True, help_text='The URL to which the package data will be forwarded after being signed.', null=True),
        ),
        migrations.AddField(
            model_name='signatureconfiguration',
            name='signed_redirect_url',
            field=models.URLField(blank=True, help_text='The page to which the user will be redirected after signing data. If this is left blank, a default page will be used.', null=True),
        ),
        migrations.AlterField(
            model_name='signatureconfiguration',
            name='allowed_domains',
            field=models.TextField(default='*', help_text='List the domains that are allowed to submit data for approval. Each domain should go on its own line. You can use wildcards ? and *. For example:<br>&nbsp;&nbsp;&nbsp; &bull; &nbsp; <code>phila.gov</code><br>&nbsp;&nbsp;&nbsp; &bull; &nbsp; <code>*.phila.gov</code><br>&nbsp;&nbsp;&nbsp; &bull; &nbsp; <code>phila.???</code>'),
        ),
    ]
